# Copyright 2022 ETH Zurich, Media Technology Center

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#   http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from typing import List, Optional

from mtc_ape_web_editor.api_types.api_types import Language
from mtc_ape_web_editor.api_types.text_segments import TextSegmentAPEOutput
from mtc_ape_web_editor.api_types.translations import APEOutputTranslation

src_text = """Die Bremer Stadtmusikanten
Es hatte ein Mann einen Esel, der schon lange Jahre die Säcke unverdrossen zur Mühle getragen hatte, dessen Kräfte aber nun zu Ende gingen, so daß er zur Arbeit immer untauglicher ward. Da dachte der Herr daran, ihn aus dem Futter zu schaffen, aber der Esel merkte, daß kein guter Wind wehte, lief fort und machte sich auf den Weg nach Bremen; dort, meinte er, könnte er ja Stadtmusikant werden. Als er ein Weilchen fortgegangen war, fand er einen Jagdhund auf dem Wege liegen, der jappte wie einer, der sich müde gelaufen hat. "Nun, was jappst du so, Packan?" fragte der Esel. "Ach," sagte der Hund, "weil ich alt bin und jeden Tag schwächer werde, auch auf der Jagd nicht mehr fort kann, hat mich mein Herr wollen totschlagen, da hab ich Reißaus genommen; aber womit soll ich nun mein Brot verdienen?" - "Weißt du was?" sprach der Esel, "ich gehe nach Bremen und werde dort Stadtmusikant, geh mit und laß dich auch bei der Musik annehmen. Ich spiele die Laute und du schlägst die Pauken." Der Hund war's zufrieden, und sie gingen weiter. Es dauerte nicht lange, so saß da eine Katze an dem Weg und macht ein Gesicht wie drei Tage Regenwetter. "Nun, was ist dir in die Quere gekommen, alter Bartputzer?" sprach der Esel. "Wer kann da lustig sein, wenn's einem an den Kragen geht," antwortete die Katze, "weil ich nun zu Jahren komme, meine Zähne stumpf werden, und ich lieber hinter dem Ofen sitze und spinne, als nach Mäusen herumjagen, hat mich meine Frau ersäufen wollen; ich habe mich zwar noch fortgemacht, aber nun ist guter Rat teuer: wo soll ich hin?" - "Geh mit uns nach Bremen, du verstehst dich doch auf die Nachtmusik, da kannst du ein Stadtmusikant werden." Die Katze hielt das für gut und ging mit. Darauf kamen die drei Landesflüchtigen an einem Hof vorbei, da saß auf dem Tor der Haushahn und schrie aus Leibeskräften. "Du schreist einem durch Mark und Bein," sprach der Esel, "was hast du vor?" - "Da hab' ich gut Wetter prophezeit," sprach der Hahn, "weil unserer lieben Frauen Tag ist, wo sie dem Christkindlein die Hemdchen gewaschen hat und sie trocknen will; aber weil morgen zum Sonntag Gäste kommen, so hat die Hausfrau doch kein Erbarmen und hat der Köchin gesagt, sie wollte mich morgen in der Suppe essen, und da soll ich mir heut abend den Kopf abschneiden lassen. Nun schrei ich aus vollem Hals, solang ich kann." - "Ei was, du Rotkopf," sagte der Esel, "zieh lieber mit uns fort, wir gehen nach Bremen, etwas Besseres als den Tod findest du überall; du hast eine gute Stimme, und wenn wir zusammen musizieren, so muß es eine Art haben." Der Hahn ließ sich den Vorschlag gefallen, und sie gingen alle vier zusammen fort.
Sie konnten aber die Stadt Bremen in einem Tag nicht erreichen und kamen abends in einen Wald, wo sie übernachten wollten. Der Esel und der Hund legten sich unter einen großen Baum, die Katze und der Hahn machten sich in die Äste, der Hahn aber flog bis an die Spitze, wo es am sichersten für ihn war. Ehe er einschlief, sah er sich noch einmal nach allen vier Winden um, da deuchte ihn, er sähe in der Ferne ein Fünkchen brennen, und rief seinen Gesellen zu, es müßte nicht gar weit ein Haus sein, denn es scheine ein Licht. Sprach der Esel: "So müssen wir uns aufmachen und noch hingehen, denn hier ist die Herberge schlecht." Der Hund meinte: "Ein paar Knochen und etwas Fleisch dran täten ihm auch gut." Also machten sie sich auf den Weg nach der Gegend, wo das Licht war, und sahen es bald heller schimmern, und es ward immer größer, bis sie vor ein helles, erleuchtetes Räuberhaus kamen. Der Esel, als der größte, näherte sich dem Fenster und schaute hinein. "Was siehst du, Grauschimmel?" fragte der Hahn. "Was ich sehe?" antwortete der Esel, "einen gedeckten Tisch mit schönem Essen und Trinken, und Räuber sitzen daran und lassen's sich wohl sein." - "Das wäre was für uns," sprach der Hahn. "Ja, ja, ach, wären wir da!" sagte der Esel. Da ratschlagten die Tiere, wie sie es anfangen müßten, um die Räuber hinauszujagen und fanden endlich ein Mittel. Der Esel mußte sich mit den Vorderfüßen auf das Fenster stellen, der Hund auf des Esels Rücken springen, die Katze auf den Hund klettern, und endlich flog der Hahn hinauf, und setzte sich der Katze auf den Kopf. Wie das geschehen war, fingen sie auf ein Zeichen insgesamt an, ihre Musik zu machen: der Esel schrie, der Hund bellte, die Katze miaute und der Hahn krähte. Dann stürzten sie durch das Fenster in die Stube hinein, daß die Scheiben klirrten. Die Räuber fuhren bei dem entsetzlichen Geschrei in die Höhe, meinten nicht anders, als ein Gespenst käme herein, und flohen in größter Furcht in den Wald hinaus. Nun setzten sich die vier Gesellen an den Tisch, nahmen mit dem vorlieb, was übriggeblieben war, und aßen nach Herzenslust.
"""

mt_text = """The Bremen Town Musicians
There was a man who had a mule that had been carrying the sacks to the mill for many years without fail, but whose strength was now running out, so that he was becoming more and more unfit for work. The master thought of taking him out of the feed, but the donkey noticed that there was no good wind, ran away and set off for Bremen; there, he thought, he could become a town musician. When he had gone a little while, he found a hunting dog lying on the road, yipping like one who has run himself tired. "Well, what are you yapping about, Packan?" asked the donkey. "Oh," said the dog, "because I'm old and getting weaker every day, and I can't go hunting anymore, my master wanted to kill me, so I ran away; but how am I supposed to earn my bread?" - "You know what?" said the donkey, "I'll go to Bremen and become a town musician there, go along and get accepted at the music as well. I'll play the lute, and you play the timpani." The dog was satisfied, and they went on their way. It was not long before a cat was sitting by the road, making a face like three days of rainy weather. "Well, what's got into your way, old beard cleaner?" said the donkey. "Who can be funny when you're in trouble," answered the cat, "because I'm getting on in years, my teeth are getting dull, and I'd rather sit behind the stove and spin than hunt around for mice, my wife wanted to drown me; I still managed to get away, but now good advice is expensive: where should I go?" - "Go with us to Bremen, you know how to play night music, there you can become a town musician." The cat thought that was good and went along. Then the three fugitives passed a farm, where the rooster was sitting on the gate and screaming at the top of his lungs. "You scream through the marrow of one's bones," said the donkey, "what are you up to?" - "I prophesied good weather," said the rooster, "because it is our dear wife's day, when she washed the little Christ's shirts and wants to dry them; but because guests are coming tomorrow on Sunday, the housewife has no mercy and has told the cook that she wants to eat me in the soup tomorrow, and that I should have my head cut off tonight. Now I'll scream at the top of my lungs as long as I can." - "Eh what, you red-head," said the donkey, "you'd better go away with us, we'll go to Bremen, you'll find something better than death anywhere; you have a good voice, andand if we make music together, it must have a way." The rooster accepted the proposal, and all four of them left together.
But they could not reach the city of Bremen in a day, and in the evening they came to a forest where they were going to spend the night. The donkey and the dog lay down under a big tree, the cat and the rooster made themselves into the branches, but the rooster flew to the top where it was safest for him. Before he fell asleep, he looked around once more to all four winds, then he thought he saw a spark burning in the distance, and called out to his companions that there must not be a house far away, for there was a light shining. Said the donkey: "So we must set out and go there, for here the inn is bad." The dog said, "A few bones and some meat on them would do him good, too." So they set out for the area where the light was, and soon saw it shimmering more brightly, and it grew larger and larger, until they came before a brightly lit robber's house. The Donkey, being the biggest, approached the window and looked in. "What do you see, gray horse?" asked the rooster. "What do I see?" replied the donkey, "a table laid with beautiful food and drink, and robbers sitting at it, enjoying themselves." - "That would be something for us," said the cock. "Yes, yes, oh, if we were there!" said the donkey. Then the animals discussed how they should begin to chase the robbers away, and at last they found a way. The donkey had to stand on the window with his front feet, the dog had to jump on the donkey's back, the cat had to climb on the dog, and finally the rooster flew up and sat on the cat's head. When this was done, at a sign they all began to make their music: the donkey brayed, the dog barked, the cat meowed, and the rooster crowed. Then they rushed through the window into the living room so that the windows rattled. The robbers took to their heights at the horrible clamor, thinking no other than that a ghost was coming in, and fled out into the forest in the greatest fear. Now the four minstrels sat down at the table, made do with what was left over, and ate to their hearts' content.
"""

ape_text = """Town Musicians of Bremen
There was a man who had a donkey that had been carrying the sacks to the mill for many years without fail, but whose strength was now running out, so that he was becoming more and more unfit for work. The master thought of taking him out of the feed, but the donkey noticed that there was no good wind, ran away and set off for Bremen; there, he thought, he could become a town musician. When he had gone a little while, he found a hound lying on the road, yipping like one who has run himself tired. "Well, what are you yapping about, Packan?" asked the donkey. "Oh," said the dog, "because I'm old and getting weaker every day, and I can't go hunting anymore, my master wanted to kill me, so I took to my heels; but what am I supposed to do for a living?" - "You know what?" said the donkey, "I'll go to Bremen and become a town musician there, go along and get accepted at the music as well. I'll play the lute, and you play the drums." The dog was satisfied, and they went on their way. It was not long before a cat was sitting by the road, making a face like three days of rainy weather. "Well, what's got into your way, old beard cleaner?" said the donkey. "Who can be funny when you're in trouble," answered the cat, "because I'm getting on in years, my teeth are getting dull, and I'd rather sit behind the stove and spin than hunt around for mice, my wife wanted to drown me; I still managed to get away, but now good advice is expensive: where should I go?" - "Go with us to Bremen, you know how to play night music, there you can become a town musician." The cat thought that was good and went along. Then the three fugitives passed a farm, where the rooster was sitting on the gate and screaming at the top of his lungs. "You scream through the marrow of one's bones," said the donkey, "what are you up to?" - "I predicted good weather," said the rooster, "because it is our dear wife's day, when she washed the little Christ's shirts and wants to dry them; but because guests are coming tomorrow on Sunday, the housewife has no mercy and has told the cook that she wants to eat me in the soup tomorrow, and that I should have my head cut off tonight. Now I'll scream at the top of my lungs as long as I can." - "Eh what, you red-head," said the donkey, "you'd better go away with us, we'll go to Bremen, you'll find something better than death anywhere; you have a good voice, and if we play music together, it must have a style." The rooster accepted the proposal, and all four of them left together.
But they could not reach the city of Bremen in a day, and in the evening they came to a forest where they were going to spend the night. The donkey and the dog lay down under a big tree, the cat and the rooster made themselves into the branches, but the rooster flew to the top where it was safest for him. Before he fell asleep, he looked around once more to all four winds, then he thought he saw a spark burning in the distance, and called out to his companions that there must not be a house far away, for there was a light shining. Said the donkey: "So we must set out and go there, for here the inn is bad." The dog said, "A few bones and some meat on them would do him good, too." So they set out for the area where the light was, and soon saw it shimmering more brightly, and it grew larger and larger, until they came before a brightly lit robber's house. The Donkey, being the biggest, approached the window and looked in. "What do you see, gray horse?" asked the rooster. "What do I see?" replied the donkey, "a table set with delicious food and drinks, and robbers sitting at it, enjoying themselves." - "That would be something for us," said the cock. "Yes, yes, oh, if we were there!" said the donkey. Then the animals discussed how they should begin to chase the robbers away, and at last they found a way. The donkey had to stand on the window with his front feet, the dog had to jump on the donkey's back, the cat had to climb on the dog, and finally the rooster flew up and sat on the cat's head. When this was done, at a sign they all began to make their music: the donkey brayed, the dog barked, the cat meowed, and the rooster crowed. Then they rushed through the window into the living room so that the windows rattled. The robbers took to their heights at the horrible clamor, thinking that a ghost was coming, and fled out into the forest in the greatest fear. Now the four musicians sat down at the table, made do with what was left over, and ate to their hearts' content.
"""


def mock_ape_output_with_id(translation_id: str) -> APEOutputTranslation:
    src_split, mt_split, ape_split = split_text(src_text), split_text(mt_text), split_text(ape_text)

    assert len(src_split) == len(mt_split)
    assert len(mt_split) == len(ape_split)

    mock_ape_segments = [
        TextSegmentAPEOutput(src_text=src, mt_text=mt, ape_text=ape)
        for src, mt, ape in zip(src_split, mt_split, ape_split)
    ]

    return APEOutputTranslation(
        id=translation_id,
        src_lang=Language.DE,
        trg_lang=Language.EN,
        text_segments=mock_ape_segments,
    )


def split_text(text: str) -> List[str]:
    return text.replace("\n", ".").replace("?", ".").replace("!", ".").split(".")


if __name__ == '__main__':
    print(f"mock_ape_output.json_dict={mock_ape_output_with_id().json_dict}")
